-- UPDATEFOTOS.dbo.CLIENTES WHERE SINCRONIZADO = 0 AND cast(fecha as date) < '2025-07-11' ;

-- UPDATEFOTOS.dbo.PEDIDOS WHERE cast(FECHA_PAGO as date) < '2025-07-11' AND SINCRONIZADO = 0 ;

-- UPDATEFOTOS.dbo.grupos_fotos WHERE CAST(FECHA AS DATE) < '2025-07-11' AND sincronizado = 0;

-- SELECT COUNT(*) FROM MYPICTURES.dbo.USUARIO WHERE SINCRONIZADO = 0;

-- SELECT FROM MYPICTURES.dbo.catalogo_fotos_venta_app WHERE SINCRONIZADO = 0 AND CAST(fecha AS DATE) < '2025-07-11';





UPDATE FOTOS.dbo.CLIENTES SET SINCRONIZADO = 1 WHERE SINCRONIZADO = 0 AND cast(fecha as date) < '2025-07-11' ;

UPDATE FOTOS.dbo.PEDIDOS SET SINCRONIZADO = 1 WHERE cast(FECHA_PAGO as date) < '2025-07-11' AND SINCRONIZADO = 0 ;

UPDATE FOTOS.dbo.grupos_fotos SET SINCRONIZADO = 1  WHERE CAST(FECHA AS DATE) < '2025-07-11' AND sincronizado = 0;

UPDATE MYPICTURES.dbo.catalogo_fotos_venta_app SET SINCRONIZADO = 2 WHERE SINCRONIZADO = 0 AND CAST(fecha AS DATE) < '2025-07-11';


SELECT * FROM 