

SELECT
    ID_GRUPO, IDLOCACION
FROM
    PEDIDOS as p
WHERE
    video_clip = 1
    AND ISNULL(ID_VENTA, 0) > 0
    AND IDLOCACION = 3
    AND CAST(FECHA AS DATE) >= '2025-06-01'
    AND ESTADO = 1
GROUP BY
    ID_GRUPO,
    IDLOCACION;